  CREATE TABLESPACE "TOTEM" DATAFILE 
  '/basedatos/u01/app/oracle/oradata/datachiloe/TOTEM.dbf' SIZE 2147483648 
  LOGGING ONLINE PERMANENT BLOCKSIZE 8192
  EXTENT MANAGEMENT LOCAL AUTOALLOCATE SEGMENT SPACE MANAGEMENT AUTO;
