--------------------------------------------------------
--  Constraints for Table DESTINO
--------------------------------------------------------

  ALTER TABLE "TOTEM"."DESTINO" MODIFY ("ID" NOT NULL ENABLE);
 
  ALTER TABLE "TOTEM"."DESTINO" MODIFY ("SALA" NOT NULL ENABLE);
 
  ALTER TABLE "TOTEM"."DESTINO" MODIFY ("PISO" NOT NULL ENABLE);
 
  ALTER TABLE "TOTEM"."DESTINO" MODIFY ("FECH_INI" NOT NULL ENABLE);
 
  ALTER TABLE "TOTEM"."DESTINO" MODIFY ("ID_ESTABLECIMIENTO" NOT NULL ENABLE);
 
  ALTER TABLE "TOTEM"."DESTINO" ADD UNIQUE ("ID")
  USING INDEX PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT)
  TABLESPACE "TOTEM"  ENABLE;
