--------------------------------------------------------
--  DDL for Table DESTINO
--------------------------------------------------------

  CREATE TABLE "TOTEM"."DESTINO" 
   (	"ID" NUMBER(10,0) NOT NULL ENABLE, 
	"SALA" VARCHAR2(100 CHAR) NOT NULL ENABLE, 
	"PISO" VARCHAR2(20 CHAR) NOT NULL ENABLE, 
	"FECH_INI" DATE DEFAULT sysdate NOT NULL ENABLE, 
	"FECH_TER" DATE, 
	"ID_ESTABLECIMIENTO" NUMBER(10,0) NOT NULL ENABLE, 
	"OBSERVACION" VARCHAR2(50 CHAR), 
	 UNIQUE ("ID")
  USING INDEX PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT)
  TABLESPACE "TOTEM"  ENABLE, 
	 CONSTRAINT "DESTINO_FK31671104190116" FOREIGN KEY ("ID_ESTABLECIMIENTO")
	  REFERENCES "TOTEM"."ESTABLECIMIENTO" ("ID_ESTABLECIMIENTO") ENABLE
   ) PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 NOCOMPRESS LOGGING
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT)
  TABLESPACE "TOTEM";
