REM INSERTING into TOTEM.ESTABLECIMIENTO
SET DEFINE OFF;
Insert into TOTEM.ESTABLECIMIENTO (ID_ESTABLECIMIENTO,NOMBRE,HOST) values ('201','HOSPITAL DE QUELLON','quellon');
Insert into TOTEM.ESTABLECIMIENTO (ID_ESTABLECIMIENTO,NOMBRE,HOST) values ('200','HOSPITAL DE ANCUD','ancud');
commit;
