--------------------------------------------------------
--  Constraints for Table GRD_CODIGOS
--------------------------------------------------------

  ALTER TABLE "TOTEM"."GRD_CODIGOS" MODIFY ("ID" NOT NULL ENABLE);
 
  ALTER TABLE "TOTEM"."GRD_CODIGOS" MODIFY ("NOMBRE_GRP" NOT NULL ENABLE);
 
  ALTER TABLE "TOTEM"."GRD_CODIGOS" MODIFY ("CODIGO" NOT NULL ENABLE);
 
  ALTER TABLE "TOTEM"."GRD_CODIGOS" MODIFY ("DESCRIPCION" NOT NULL ENABLE);
 
  ALTER TABLE "TOTEM"."GRD_CODIGOS" MODIFY ("FEC_INICIO" NOT NULL ENABLE);
 
  ALTER TABLE "TOTEM"."GRD_CODIGOS" ADD CONSTRAINT "TIPOS_DOCUMENTOS_PK" PRIMARY KEY ("ID")
  USING INDEX PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT)
  TABLESPACE "TOTEM"  ENABLE;
