  CREATE TABLE "TOTEM"."MARCAS" 
   (	"ID" NUMBER(10,0) NOT NULL ENABLE, 
	"RUT" VARCHAR2(10 CHAR), 
	"DV" VARCHAR2(2 CHAR), 
	"NOMBRE" VARCHAR2(100 CHAR) NOT NULL ENABLE, 
	"APELLIDO_P" VARCHAR2(30 CHAR) NOT NULL ENABLE, 
	"APELLIDO_M" VARCHAR2(30 CHAR) NOT NULL ENABLE, 
	"F_ACCESO" DATE DEFAULT sysdate NOT NULL ENABLE, 
	"ACTIVO" VARCHAR2(1 CHAR) DEFAULT 'S' NOT NULL ENABLE, 
	"ID_DESTINO" NUMBER(10,0) NOT NULL ENABLE, 
	"PASAPORTE" VARCHAR2(100 CHAR), 
	"CODIGO_PAIS" VARCHAR2(2 CHAR), 
	 UNIQUE ("ID")
  USING INDEX PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT)
  TABLESPACE "TOTEM"  ENABLE, 
	 CONSTRAINT "MARCAS_FK21672150623083" FOREIGN KEY ("ID_DESTINO")
	  REFERENCES "TOTEM"."DESTINO" ("ID") ENABLE
   ) PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 NOCOMPRESS LOGGING
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT)
  TABLESPACE "TOTEM" 
