PROMPT CREAR TABLA RESTRICCIONES;

  CREATE TABLE "TOTEM"."RESTRICCIONES" 
   (	"ID" NUMBER NOT NULL ENABLE, 
	"CLAVE" VARCHAR2(100 CHAR) NOT NULL ENABLE, 
	"VALOR" VARCHAR2(100 CHAR) NOT NULL ENABLE, 
	"ENTIDAD" VARCHAR2(100 CHAR) NOT NULL ENABLE, 
	"FEC_DESDE" DATE NOT NULL ENABLE, 
	"FEC_HASTA" VARCHAR2(20),
	"FAMILIA_CLAVE" VARCHAR2(10)
   ) PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 NOCOMPRESS LOGGING
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT)
  TABLESPACE "TOTEM" 
  / 

   COMMENT ON COLUMN "TOTEM"."RESTRICCIONES"."ID" IS 'IDENTIFICADOR DE RESTRICCION'
   /
   COMMENT ON COLUMN "TOTEM"."RESTRICCIONES"."CLAVE" IS 'CLAVE ASOCIDA A UNA RESTRICCION'
   / 
   COMMENT ON COLUMN "TOTEM"."RESTRICCIONES"."VALOR" IS 'VALOR DE LA RESTRICCIÓN'
   /
   COMMENT ON COLUMN "TOTEM"."RESTRICCIONES"."ENTIDAD" IS 'ENTIDAD DE RESTRICCIÓN'
   /
   COMMENT ON COLUMN "TOTEM"."RESTRICCIONES"."FEC_DESDE" IS 'FECHA INICIO RESTRICCIÓN'
   /
   COMMENT ON COLUMN "TOTEM"."RESTRICCIONES"."FEC_HASTA" IS 'FECHA FIN RESTRICCION, UN VALOR NULL INIDCA RESTRICCIÓN VIGENTE'
   /
   COMMENT ON COLUMN "TOTEM"."RESTRICCIONES"."FAMILIA_CLAVE" IS 'Indica si la clave asociada a la restricción corresponde a un RUT o PASAPORTE'
   /
   COMMENT ON TABLE "TOTEM"."RESTRICCIONES"  IS 'Entidad que permite especificar restriciones asociadas a las personas. Ejemplo rut a los cuales negar un acceso ligado a personas definidas en la entidad personas'
/
