CREATE TABLE "TOTEM"."GRD_CODIGOS" 
   (	"ID" NUMBER NOT NULL ENABLE, 
	"ID_GRP" NUMBER, 
	"NOMBRE_GRP" VARCHAR2(100 CHAR) NOT NULL ENABLE, 
	"CODIGO" VARCHAR2(20 CHAR) NOT NULL ENABLE, 
	"DESCRIPCION" VARCHAR2(100 CHAR) NOT NULL ENABLE, 
	"ORDEN" NUMBER, 
	"FEC_INICIO" DATE NOT NULL ENABLE, 
	"FEC_FIN" DATE, 
	 CONSTRAINT "TIPOS_DOCUMENTOS_PK" PRIMARY KEY ("ID")
  USING INDEX PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT)
  TABLESPACE "TOTEM"  ENABLE
   ) PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 NOCOMPRESS LOGGING
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT)
  TABLESPACE "TOTEM" 
 

   COMMENT ON COLUMN "TOTEM"."GRD_CODIGOS"."ID" IS 'identificador de item'
 
   COMMENT ON COLUMN "TOTEM"."GRD_CODIGOS"."ID_GRP" IS 'identificador de grupo'
 
   COMMENT ON COLUMN "TOTEM"."GRD_CODIGOS"."NOMBRE_GRP" IS 'nombre del grupo de códigos'
 
   COMMENT ON COLUMN "TOTEM"."GRD_CODIGOS"."CODIGO" IS 'código de un item del grupo'
 
   COMMENT ON COLUMN "TOTEM"."GRD_CODIGOS"."DESCRIPCION" IS 'texto a mostrar asociado al código del item del grupo'
 
   COMMENT ON COLUMN "TOTEM"."GRD_CODIGOS"."ORDEN" IS 'Numero que estable un orden entre los item del grupo'
 
   COMMENT ON COLUMN "TOTEM"."GRD_CODIGOS"."FEC_INICIO" IS 'Fecha de inicio de vigencia del item'
 
   COMMENT ON COLUMN "TOTEM"."GRD_CODIGOS"."FEC_FIN" IS 'Fecha de termino vigencia del item del grupo. Un valor null indica item vigente'
 
   COMMENT ON TABLE "TOTEM"."GRD_CODIGOS"  IS 'Entidad de conetiene grupos de códigos para el sistema'
 

