INSERT INTO destino (id,sala,piso,fech_ini,fech_ter,id_establecimiento,observacion) values (7,'SALUD MENTAL + CORTA ESTADIA PSIQUIATRICA',-1,SYSDATE,NULL,201,NULL);
INSERT INTO destino (id,sala,piso,fech_ini,fech_ter,id_establecimiento,observacion) values (8,'URGENCIA',1,SYSDATE,NULL,201,NULL);
INSERT INTO destino (id,sala,piso,fech_ini,fech_ter,id_establecimiento,observacion) values (9,'SAMU',1,SYSDATE,NULL,201,NULL);
INSERT INTO destino (id,sala,piso,fech_ini,fech_ter,id_establecimiento,observacion) values (10,'CAMARA HIPERBARICA',1,SYSDATE,NULL,201,NULL);
INSERT INTO destino (id,sala,piso,fech_ini,fech_ter,id_establecimiento,observacion) values (11,'MORGUE',1,SYSDATE,NULL,201,NULL);
INSERT INTO destino (id,sala,piso,fech_ini,fech_ter,id_establecimiento,observacion) values (12,'ESTERILIZACION',1,SYSDATE,NULL,201,NULL);
INSERT INTO destino (id,sala,piso,fech_ini,fech_ter,id_establecimiento,observacion) values (13,'PABELLONES',1,SYSDATE,NULL,201,NULL);
INSERT INTO destino (id,sala,piso,fech_ini,fech_ter,id_establecimiento,observacion) values (14,'IMAGENOLOGIA',1,SYSDATE,NULL,201,NULL);
INSERT INTO destino (id,sala,piso,fech_ini,fech_ter,id_establecimiento,observacion) values (15,'MEDICINA FISICA',1,SYSDATE,NULL,201,NULL);
INSERT INTO destino (id,sala,piso,fech_ini,fech_ter,id_establecimiento,observacion) values (16,'SOME',1,SYSDATE,NULL,201,NULL);
INSERT INTO destino (id,sala,piso,fech_ini,fech_ter,id_establecimiento,observacion) values (17,'HEMODIALISIS',1,SYSDATE,NULL,201,NULL);
INSERT INTO destino (id,sala,piso,fech_ini,fech_ter,id_establecimiento,observacion) values (18,'FARMACIA',1,SYSDATE,NULL,201,NULL);
INSERT INTO destino (id,sala,piso,fech_ini,fech_ter,id_establecimiento,observacion) values (19,'LABORATORIO',1,SYSDATE,NULL,201,NULL);
INSERT INTO destino (id,sala,piso,fech_ini,fech_ter,id_establecimiento,observacion) values (20,'CENTRAL ALIMENTACION',1,SYSDATE,NULL,201,NULL);
INSERT INTO destino (id,sala,piso,fech_ini,fech_ter,id_establecimiento,observacion) values (21,'SEDILE',1,SYSDATE,NULL,201,NULL);
INSERT INTO destino (id,sala,piso,fech_ini,fech_ter,id_establecimiento,observacion) values (22,'LAVANDERIA',1,SYSDATE,NULL,201,NULL);
INSERT INTO destino (id,sala,piso,fech_ini,fech_ter,id_establecimiento,observacion) values (23,'BODEGA CENTRAL ABASTECIMEINTO',1,SYSDATE,NULL,201,NULL);
INSERT INTO destino (id,sala,piso,fech_ini,fech_ter,id_establecimiento,observacion) values (24,'CONSULTA DENTAL',2,SYSDATE,NULL,201,NULL);
INSERT INTO destino (id,sala,piso,fech_ini,fech_ter,id_establecimiento,observacion) values (25,'ENDOSCOPIA',2,SYSDATE,NULL,201,NULL);
INSERT INTO destino (id,sala,piso,fech_ini,fech_ter,id_establecimiento,observacion) values (26,'LABORATORIO DENTAL',2,SYSDATE,NULL,201,NULL);
INSERT INTO destino (id,sala,piso,fech_ini,fech_ter,id_establecimiento,observacion) values (27,'PROCEDIMIENTOS NO MEDICO',2,SYSDATE,NULL,201,NULL);
INSERT INTO destino (id,sala,piso,fech_ini,fech_ter,id_establecimiento,observacion) values (28,'CONSULTAS MEDICAS',2,SYSDATE,NULL,201,NULL);
INSERT INTO destino (id,sala,piso,fech_ini,fech_ter,id_establecimiento,observacion) values (29,'ADMINISTRACION ATENCION ABIERTA',2,SYSDATE,NULL,201,NULL);
INSERT INTO destino (id,sala,piso,fech_ini,fech_ter,id_establecimiento,observacion) values (30,'HOSPITALIZACION GINECOLOGICA Y OBSTETRICIA',2,SYSDATE,NULL,201,NULL);
INSERT INTO destino (id,sala,piso,fech_ini,fech_ter,id_establecimiento,observacion) values (31,'HOSPITALIZACION PEDIATRICA+CIRUGIA INFANTIL',2,SYSDATE,NULL,201,NULL);
INSERT INTO destino (id,sala,piso,fech_ini,fech_ter,id_establecimiento,observacion) values (32,'HOSPITALIZACION MEDICINA INTERNA',2,SYSDATE,NULL,201,NULL);
INSERT INTO destino (id,sala,piso,fech_ini,fech_ter,id_establecimiento,observacion) values (33,'HOSPITALIZACION MEDICINA INTERNA + CIRUGIA GENERAL',2,SYSDATE,NULL,201,NULL);
INSERT INTO destino (id,sala,piso,fech_ini,fech_ter,id_establecimiento,observacion) values (34,'HOSPITALIZACION AISLAMIENTO',2,SYSDATE,NULL,201,NULL);
INSERT INTO destino (id,sala,piso,fech_ini,fech_ter,id_establecimiento,observacion) values (35,'HOSPITALIZACION MEDICINA INTERNA + CIRUGIA GENERAL',2,SYSDATE,NULL,201,NULL);
INSERT INTO destino (id,sala,piso,fech_ini,fech_ter,id_establecimiento,observacion) values (36,'MANSARDA DIRECCION + ADMINISTRACION',3,SYSDATE,NULL,201,NULL);
