DROP SEQUENCE "TOTEM"."SQ_MARCA";
DROP SEQUENCE "TOTEM"."SQ_PERSONA";
DROP TABLE "TOTEM"."DESTINO" cascade constraints;
DROP TABLE "TOTEM"."ESTABLECIMIENTO" cascade constraints;
DROP TABLE "TOTEM"."GRD_CODIGOS" cascade constraints;
DROP TABLE "TOTEM"."MARCAS" cascade constraints;
DROP TABLE "TOTEM"."PERSONAS" cascade constraints;
DROP PROCEDURE "TOTEM"."SET_SEQUENCE_NEXTVAL";
