--------------------------------------------------------
--  Constraints for Table PERSONAS
--------------------------------------------------------

  ALTER TABLE "TOTEM"."PERSONAS" MODIFY ("NOMBRE" NOT NULL ENABLE)
 
  ALTER TABLE "TOTEM"."PERSONAS" ADD UNIQUE ("RUT")
  USING INDEX PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT)
  TABLESPACE "TOTEM"  ENABLE
