--------------------------------------------------------
--  DDL for Index TIPOS_DOCUMENTOS_PK
--------------------------------------------------------

  CREATE UNIQUE INDEX "TOTEM"."TIPOS_DOCUMENTOS_PK" ON "TOTEM"."GRD_CODIGOS" ("ID") 
  PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT)
  TABLESPACE "TOTEM"
